{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "rmap.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "rmap.fullname" . }}
  labels:
    {{- include "rmap.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rmap.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
