{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "rmap.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "rmap.fullname" . }}
  labels:
    {{- include "rmap.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "rmap.selectorLabels" . | nindent 6 }}
      component: api
{{- end }}
