{{- if not .Values.secrets.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmap.secretName" . }}
  labels:
    {{- include "rmap.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
